# List of known safe domains to trust automatically.
# The matching function strips "www." prefixes, so you only need to list the base domain.

SAFE_DOMAINS = {
    # ═══════════════════════════════════════════════════════════════
    # SEARCH ENGINES
    # ═══════════════════════════════════════════════════════════════
    "google.com", "google.co.uk", "google.co.in", "google.ca", "google.com.au",
    "google.de", "google.fr", "google.co.jp", "google.com.br", "google.es",
    "bing.com",
    "yahoo.com", "yahoo.co.jp",
    "duckduckgo.com",
    "baidu.com",
    "yandex.com", "yandex.ru",
    "ask.com",
    "ecosia.org",
    "brave.com",
    "startpage.com",
    "search.yahoo.com",

    # ═══════════════════════════════════════════════════════════════
    # SOCIAL MEDIA
    # ═══════════════════════════════════════════════════════════════
    "facebook.com", "fb.com", "fb.me",
    "instagram.com",
    "twitter.com", "x.com",
    "linkedin.com",
    "pinterest.com",
    "reddit.com",
    "tiktok.com",
    "snapchat.com",
    "whatsapp.com", "web.whatsapp.com",
    "telegram.org", "t.me",
    "discord.com", "discord.gg",
    "youtube.com", "youtu.be",
    "vimeo.com",
    "twitch.tv",
    "tumblr.com",
    "quora.com",
    "mastodon.social",
    "threads.net",
    "wechat.com",
    "weibo.com",
    "line.me",
    "signal.org",
    "viber.com",
    "meetup.com",
    "nextdoor.com",
    "clubhouse.com",
    "meta.com",

    # ═══════════════════════════════════════════════════════════════
    # E-COMMERCE & RETAIL
    # ═══════════════════════════════════════════════════════════════
    "amazon.com", "amazon.co.uk", "amazon.in", "amazon.de", "amazon.ca",
    "amazon.co.jp", "amazon.fr", "amazon.es", "amazon.it", "amazon.com.au",
    "amazon.com.br", "amazon.sg",
    "ebay.com", "ebay.co.uk", "ebay.de",
    "walmart.com",
    "target.com",
    "bestbuy.com",
    "alibaba.com",
    "aliexpress.com",
    "flipkart.com",
    "etsy.com",
    "shopify.com",
    "costco.com",
    "homedepot.com",
    "lowes.com",
    "macys.com",
    "nordstrom.com",
    "zappos.com",
    "wayfair.com",
    "overstock.com",
    "newegg.com",
    "bhphotovideo.com",
    "ikea.com",
    "zara.com",
    "hm.com",
    "uniqlo.com",
    "nike.com",
    "adidas.com",
    "puma.com",
    "underarmour.com",
    "jcpenney.com",
    "kohls.com",
    "sephora.com",
    "ulta.com",
    "wish.com",
    "shein.com",
    "temu.com",
    "mercadolibre.com",
    "rakuten.com",
    "asos.com",
    "gap.com",
    "oldnavy.com",
    "bathandbodyworks.com",
    "chewy.com",
    "craigslist.org",

    # ═══════════════════════════════════════════════════════════════
    # TECHNOLOGY & SOFTWARE
    # ═══════════════════════════════════════════════════════════════
    "microsoft.com", "live.com", "office.com", "office365.com",
    "outlook.com", "onedrive.com", "azure.com", "visualstudio.com",
    "windows.com", "xbox.com", "bing.com", "msn.com",
    "apple.com", "icloud.com", "itunes.com",
    "google.com", "gmail.com", "android.com", "chromium.org",
    "github.com", "github.io",
    "gitlab.com",
    "bitbucket.org",
    "stackoverflow.com", "stackexchange.com", "askubuntu.com", "superuser.com",
    "serverfault.com",
    "adobe.com",
    "oracle.com",
    "ibm.com",
    "intel.com",
    "nvidia.com",
    "amd.com",
    "samsung.com",
    "dell.com",
    "hp.com", "hpe.com",
    "lenovo.com",
    "asus.com",
    "corsair.com",
    "razer.com",
    "logitech.com",
    "dropbox.com",
    "box.com",
    "slack.com",
    "zoom.us",
    "atlassian.com", "jira.com", "trello.com", "bitbucket.org", "confluence.com",
    "salesforce.com",
    "hubspot.com",
    "zendesk.com",
    "freshdesk.com",
    "servicenow.com",
    "vmware.com",
    "docker.com",
    "redhat.com",
    "canonical.com", "ubuntu.com",
    "debian.org",
    "fedoraproject.org",
    "archlinux.org",
    "linuxfoundation.org",
    "mozilla.org", "firefox.com",
    "opera.com",
    "vivaldi.com",
    "brave.com",
    "jetbrains.com",
    "sublimetext.com",
    "notepad-plus-plus.org",
    "python.org",
    "nodejs.org",
    "npmjs.com",
    "pypi.org",
    "rust-lang.org",
    "golang.org", "go.dev",
    "ruby-lang.org",
    "php.net",
    "java.com",
    "kotlin.dev",
    "swift.org",
    "typescriptlang.org",
    "reactjs.org",
    "angular.io", "angular.dev",
    "vuejs.org",
    "nextjs.org",
    "vercel.com",
    "netlify.com",
    "heroku.com",
    "digitalocean.com",
    "linode.com",
    "vultr.com",
    "cloudflare.com",
    "fastly.com",
    "akamai.com",
    "godaddy.com",
    "namecheap.com",
    "domains.google",
    "porkbun.com",
    "hover.com",
    "1password.com",
    "lastpass.com",
    "bitwarden.com",
    "dashlane.com",
    "keepersecurity.com",
    "okta.com",
    "auth0.com",
    "twilio.com",
    "sendgrid.com",
    "mailchimp.com",
    "intercom.com",
    "figma.com",
    "canva.com",
    "sketch.com",
    "invisionapp.com",
    "miro.com",
    "notion.so",
    "notion.com",
    "airtable.com",
    "asana.com",
    "monday.com",
    "clickup.com",
    "basecamp.com",
    "todoist.com",
    "evernote.com",
    "obsidian.md",

    # ═══════════════════════════════════════════════════════════════
    # CLOUD & HOSTING
    # ═══════════════════════════════════════════════════════════════
    "aws.amazon.com", "amazonaws.com",
    "azure.microsoft.com",
    "cloud.google.com",
    "firebase.google.com", "firebaseio.com",
    "supabase.com",
    "mongodb.com",
    "elastic.co", "elasticsearch.org",
    "redis.io",
    "postgresql.org",
    "mysql.com",
    "mariadb.org",
    "sqlite.org",
    "couchbase.com",
    "neo4j.com",
    "influxdata.com",
    "grafana.com",
    "datadog.com",
    "splunk.com",
    "newrelic.com",
    "sentry.io",
    "pagerduty.com",
    "terraform.io",
    "ansible.com",
    "puppet.com",
    "chef.io",
    "kubernetes.io",
    "helm.sh",
    "istio.io",
    "jenkins.io",
    "circleci.com",
    "travis-ci.com", "travis-ci.org",
    "github.com",
    "gitlab.com",

    # ═══════════════════════════════════════════════════════════════
    # STREAMING & ENTERTAINMENT
    # ═══════════════════════════════════════════════════════════════
    "netflix.com",
    "hulu.com",
    "disneyplus.com", "disney.com",
    "hbomax.com", "max.com",
    "peacocktv.com",
    "paramountplus.com",
    "primevideo.com",
    "crunchyroll.com",
    "funimation.com",
    "spotify.com",
    "soundcloud.com",
    "pandora.com",
    "deezer.com",
    "tidal.com",
    "applemusic.com", "music.apple.com",
    "shazam.com",
    "imdb.com",
    "rottentomatoes.com",
    "letterboxd.com",
    "goodreads.com",
    "audible.com",
    "kindle.com",
    "twitch.tv",
    "steampowered.com", "store.steampowered.com",
    "epicgames.com",
    "gog.com",
    "ea.com",
    "ubisoft.com",
    "riotgames.com",
    "blizzard.com", "battle.net",
    "playstation.com",
    "xbox.com",
    "nintendo.com",
    "roblox.com",
    "minecraft.net",
    "mojang.com",

    # ═══════════════════════════════════════════════════════════════
    # NEWS & MEDIA
    # ═══════════════════════════════════════════════════════════════
    "nytimes.com",
    "washingtonpost.com",
    "cnn.com",
    "bbc.com", "bbc.co.uk",
    "foxnews.com",
    "nbcnews.com", "nbc.com",
    "cbsnews.com", "cbs.com",
    "abcnews.go.com", "abc.com",
    "reuters.com",
    "apnews.com",
    "bloomberg.com",
    "forbes.com",
    "businessinsider.com",
    "cnbc.com",
    "wsj.com",
    "ft.com",
    "economist.com",
    "theguardian.com",
    "independent.co.uk",
    "telegraph.co.uk",
    "dailymail.co.uk",
    "usatoday.com",
    "latimes.com",
    "chicagotribune.com",
    "nypost.com",
    "huffpost.com",
    "buzzfeed.com",
    "vice.com",
    "vox.com",
    "theatlantic.com",
    "newyorker.com",
    "time.com",
    "newsweek.com",
    "politico.com",
    "thehill.com",
    "npr.org",
    "pbs.org",
    "aljazeera.com",
    "dw.com",
    "france24.com",
    "hindustantimes.com",
    "timesofindia.indiatimes.com", "indiatimes.com",
    "ndtv.com",
    "weather.com",
    "accuweather.com",
    "medium.com",
    "substack.com",
    "techcrunch.com",
    "theverge.com",
    "wired.com",
    "arstechnica.com",
    "mashable.com",
    "engadget.com",
    "cnet.com",
    "zdnet.com",
    "tomsguide.com",
    "tomshardware.com",
    "pcmag.com",
    "macrumors.com",
    "9to5mac.com",
    "gizmodo.com",

    # ═══════════════════════════════════════════════════════════════
    # BANKING & FINANCE
    # ═══════════════════════════════════════════════════════════════
    "paypal.com",
    "stripe.com",
    "square.com", "squareup.com",
    "venmo.com",
    "wise.com",
    "revolut.com",
    "chase.com",
    "bankofamerica.com",
    "wellsfargo.com",
    "citibank.com", "citigroup.com",
    "capitalone.com",
    "usbank.com",
    "tdbank.com",
    "pnc.com",
    "goldmansachs.com",
    "morganstanley.com",
    "jpmorgan.com",
    "americanexpress.com",
    "discover.com",
    "visa.com",
    "mastercard.com",
    "hsbc.com",
    "barclays.co.uk", "barclays.com",
    "standardchartered.com",
    "ubs.com",
    "creditsuisse.com",
    "deutschebank.com",
    "bnpparibas.com",
    "ing.com",
    "rabobank.com",
    "commerzbank.com",
    "robinhood.com",
    "etrade.com",
    "schwab.com",
    "fidelity.com",
    "vanguard.com",
    "tdameritrade.com",
    "interactivebrokers.com",
    "coinbase.com",
    "binance.com",
    "kraken.com",
    "gemini.com",
    "crypto.com",
    "blockchain.com",
    "mint.com",
    "nerdwallet.com",
    "creditkarma.com",
    "experian.com",
    "equifax.com",
    "transunion.com",
    "plaid.com",

    # ═══════════════════════════════════════════════════════════════
    # EDUCATION
    # ═══════════════════════════════════════════════════════════════
    "harvard.edu",
    "mit.edu",
    "stanford.edu",
    "yale.edu",
    "princeton.edu",
    "columbia.edu",
    "uchicago.edu",
    "upenn.edu",
    "caltech.edu",
    "berkeley.edu",
    "cornell.edu",
    "nyu.edu",
    "usc.edu",
    "ucla.edu",
    "umich.edu",
    "cmu.edu",
    "gatech.edu",
    "oxford.ac.uk",
    "cam.ac.uk",
    "imperial.ac.uk",
    "ucl.ac.uk",
    "lse.ac.uk",
    "coursera.org",
    "udemy.com",
    "edx.org",
    "khanacademy.org",
    "udacity.com",
    "pluralsight.com",
    "skillshare.com",
    "lynda.com",
    "codecademy.com",
    "freecodecamp.org",
    "w3schools.com",
    "geeksforgeeks.org",
    "hackerrank.com",
    "leetcode.com",
    "codewars.com",
    "brilliant.org",
    "duolingo.com",
    "babbel.com",
    "rosettastone.com",
    "academia.edu",
    "researchgate.net",
    "scholar.google.com",
    "arxiv.org",
    "sciencedirect.com",
    "springer.com",
    "nature.com",
    "ieee.org",
    "acm.org",

    # ═══════════════════════════════════════════════════════════════
    # GOVERNMENT
    # ═══════════════════════════════════════════════════════════════
    "usa.gov",
    "whitehouse.gov",
    "congress.gov",
    "irs.gov",
    "ssa.gov",
    "cdc.gov",
    "nih.gov",
    "fda.gov",
    "epa.gov",
    "nasa.gov",
    "noaa.gov",
    "fbi.gov",
    "dhs.gov",
    "state.gov",
    "treasury.gov",
    "ed.gov",
    "va.gov",
    "sec.gov",
    "ftc.gov",
    "fcc.gov",
    "gov.uk",
    "nhs.uk",
    "canada.ca",
    "india.gov.in",
    "europa.eu",
    "un.org",
    "who.int",
    "worldbank.org",
    "imf.org",

    # ═══════════════════════════════════════════════════════════════
    # TRAVEL & MAPS
    # ═══════════════════════════════════════════════════════════════
    "maps.google.com", "google.com/maps",
    "waze.com",
    "openstreetmap.org",
    "booking.com",
    "expedia.com",
    "airbnb.com",
    "hotels.com",
    "tripadvisor.com",
    "kayak.com",
    "skyscanner.com",
    "priceline.com",
    "orbitz.com",
    "vrbo.com",
    "trivago.com",
    "agoda.com",
    "marriott.com",
    "hilton.com",
    "ihg.com",
    "hyatt.com",
    "wyndhamhotels.com",
    "united.com",
    "aa.com",
    "delta.com",
    "southwest.com",
    "jetblue.com",
    "spirit.com",
    "britishairways.com",
    "lufthansa.com",
    "emirates.com",
    "qatarairways.com",
    "singaporeair.com",
    "flightradar24.com",
    "uber.com",
    "lyft.com",
    "grab.com",
    "ola.com",

    # ═══════════════════════════════════════════════════════════════
    # EMAIL PROVIDERS
    # ═══════════════════════════════════════════════════════════════
    "gmail.com", "mail.google.com",
    "outlook.com", "outlook.live.com",
    "hotmail.com",
    "yahoo.com", "mail.yahoo.com",
    "protonmail.com", "proton.me",
    "tutanota.com",
    "zoho.com", "mail.zoho.com",
    "fastmail.com",
    "aol.com",
    "icloud.com",
    "gmx.com",
    "mail.com",
    "yandex.mail",

    # ═══════════════════════════════════════════════════════════════
    # TELECOM
    # ═══════════════════════════════════════════════════════════════
    "att.com",
    "verizon.com",
    "t-mobile.com",
    "sprint.com",
    "comcast.com", "xfinity.com",
    "spectrum.com",
    "cox.com",
    "centurylink.com",
    "vodafone.com",
    "o2.co.uk",
    "three.co.uk",
    "bt.com",
    "jio.com",
    "airtel.in",

    # ═══════════════════════════════════════════════════════════════
    # FOOD & DELIVERY
    # ═══════════════════════════════════════════════════════════════
    "doordash.com",
    "ubereats.com",
    "grubhub.com",
    "postmates.com",
    "instacart.com",
    "deliveroo.com",
    "justeat.com",
    "seamless.com",
    "dominos.com",
    "pizzahut.com",
    "mcdonalds.com",
    "starbucks.com",
    "chipotle.com",
    "subway.com",
    "chick-fil-a.com",
    "burgerking.com",
    "wendys.com",
    "dunkindonuts.com",
    "papajohns.com",
    "tacobell.com",

    # ═══════════════════════════════════════════════════════════════
    # HEALTH & FITNESS
    # ═══════════════════════════════════════════════════════════════
    "webmd.com",
    "mayoclinic.org",
    "healthline.com",
    "medlineplus.gov",
    "clevelandclinic.org",
    "hopkinsmedicine.org",
    "fitbit.com",
    "myfitnesspal.com",
    "strava.com",
    "peloton.com",
    "garmin.com",
    "noom.com",
    "calm.com",
    "headspace.com",
    "zocdoc.com",
    "goodrx.com",
    "cvs.com",
    "walgreens.com",

    # ═══════════════════════════════════════════════════════════════
    # AUTOMOTIVE
    # ═══════════════════════════════════════════════════════════════
    "tesla.com",
    "ford.com",
    "chevrolet.com", "gm.com",
    "toyota.com",
    "honda.com",
    "bmw.com",
    "mercedes-benz.com",
    "audi.com",
    "volkswagen.com",
    "hyundai.com",
    "kia.com",
    "nissan.com",
    "subaru.com",
    "mazda.com",
    "porsche.com",
    "carvana.com",
    "carmax.com",
    "autotrader.com",
    "cars.com",
    "edmunds.com",
    "kbb.com",

    # ═══════════════════════════════════════════════════════════════
    # REAL ESTATE
    # ═══════════════════════════════════════════════════════════════
    "zillow.com",
    "realtor.com",
    "redfin.com",
    "trulia.com",
    "apartments.com",
    "rightmove.co.uk",
    "zoopla.co.uk",
    "compass.com",
    "coldwellbanker.com",
    "century21.com",
    "opendoor.com",

    # ═══════════════════════════════════════════════════════════════
    # PRODUCTIVITY & COMMUNICATIONS
    # ═══════════════════════════════════════════════════════════════
    "docs.google.com", "drive.google.com", "sheets.google.com",
    "calendar.google.com", "meet.google.com",
    "teams.microsoft.com",
    "zoom.us",
    "webex.com",
    "gotomeeting.com",
    "grammarly.com",
    "wordreference.com",
    "translate.google.com",
    "deepl.com",
    "typeform.com",
    "surveymonkey.com",
    "doodle.com",
    "calendly.com",
    "loom.com",
    "prezi.com",
    "slideshare.net",

    # ═══════════════════════════════════════════════════════════════
    # SECURITY & ANTIVIRUS
    # ═══════════════════════════════════════════════════════════════
    "norton.com",
    "mcafee.com",
    "kaspersky.com",
    "avast.com",
    "avg.com",
    "malwarebytes.com",
    "bitdefender.com",
    "sophos.com",
    "trendmicro.com",
    "crowdstrike.com",
    "paloaltonetworks.com",
    "fortinet.com",
    "checkpoint.com",
    "virustotal.com",
    "haveibeenpwned.com",
    "letsencrypt.org",

    # ═══════════════════════════════════════════════════════════════
    # MISCELLANEOUS / POPULAR
    # ═══════════════════════════════════════════════════════════════
    "wikipedia.org", "wikimedia.org", "wiktionary.org",
    "archive.org",
    "yelp.com",
    "yellowpages.com",
    "bbb.org",
    "patreon.com",
    "gofundme.com",
    "kickstarter.com",
    "indiegogo.com",
    "change.org",
    "ted.com",
    "imgur.com",
    "giphy.com",
    "unsplash.com",
    "pexels.com",
    "shutterstock.com",
    "gettyimages.com",
    "istockphoto.com",
    "flickr.com",
    "deviantart.com",
    "dribbble.com",
    "behance.net",
    "500px.com",
    "kaggle.com",
    "huggingface.co",
    "openai.com",
    "anthropic.com",
    "deepmind.com", "deepmind.google",
    "colab.research.google.com",
    "wolframalpha.com",
    "mathway.com",
    "desmos.com",
    "symbolab.com",
    "speedtest.net",
    "fast.com",
    "whois.net",
    "dnsstuff.com",
    "whatismyipaddress.com",
    "ipinfo.io",
}


def is_safe_domain(domain: str) -> bool:
    """
    Check if a domain (or any of its parent domains) is in the safe list.
    Strips 'www.' prefix and performs suffix matching so that
    'mail.google.com' is recognized as safe because 'google.com' is in the list.
    """
    if not domain:
        return False

    domain = domain.lower().strip()

    # Strip www. prefix
    if domain.startswith("www."):
        domain = domain[4:]

    # Direct match
    if domain in SAFE_DOMAINS:
        return True

    # Suffix match: check if any parent domain is in the safe list
    # e.g., "docs.google.com" → check "google.com"
    parts = domain.split(".")
    for i in range(1, len(parts) - 1):
        parent = ".".join(parts[i:])
        if parent in SAFE_DOMAINS:
            return True

    return False
